using OKX.Net.Enums;

namespace OKX.Net.Converters;

internal class FundingBillTypeConverter : BaseConverter<OKXFundingBillType>
{
    public FundingBillTypeConverter() : this(true) { }
    public FundingBillTypeConverter(bool quotes) : base(quotes) { }

    protected override List<KeyValuePair<OKXFundingBillType, string>> Mapping => new List<KeyValuePair<OKXFundingBillType, string>>
    {
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.Deposit, "1"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.Withdrawal, "2"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.CanceledWithdrawal, "13"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferToFutures, "18"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferFromFutures, "19"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferToSubAccount, "20"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferFromSubAccount, "21"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.Claim, "28"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferToMargin, "33"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferFromMargin, "34"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferToSpot, "37"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferFromSpot, "38"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TradingFeesSettledByLoyaltyPoints, "41"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.LoyaltyPointsPurchase, "42"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.SystemReversal, "47"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.ReceivedFromActivities, "48"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.GivenAwayToActivities, "49"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.ReceivedFromAppointments, "50"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.DeductedFromAppointments, "51"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.RedPacketSent, "52"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.RedPacketSnatched, "53"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.RedPacketRefunded, "54"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferToPerpetual, "55"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferFromPerpetual, "56"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferFromHedgingAccount, "59"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferToHedgingAccount, "60"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.Conversion, "61"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferToOptions, "63"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferFromOptions, "62"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.ClaimRebateCard, "68"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.DistributeRebateCard, "69"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TokenReceived, "72"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TokenGivenAway, "73"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TokenRefunded, "74"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.SubscriptionToSavings, "75"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.RedemptionToSavings, "76"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.Distribute, "77"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.LockUp, "78"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.NodeVoting, "79"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.Staking80, "80"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.VoteRedemption, "81"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.StakingRedemption82, "82"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.StakingYield, "83"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.ViolationFee, "84"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.PowMiningYield, "85"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.CloudMiningPay, "86"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.CloudMiningYield, "87"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.Subsidy, "88"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.Staking89, "89"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.StakingSubscription, "90"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.StakingRedemption91, "91"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.AddCollateral, "92"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.RedeemCollateral, "93"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.Investment, "94"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.BorrowerBorrows, "95"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.PrincipalTransferredIn, "96"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.BorrowerTransferredLoanOut, "97"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.BorrowerTransferredInterestOut, "98"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.InvestorTransferredInterestIn, "99"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.PrepaymentPenaltyTransferredIn, "102"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.PrepaymentPenaltyTransferredOut, "103"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.FeeTransferredIn, "104"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.FeeTransferredOut, "105"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.OverdueFeeTransferredIn, "106"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.OverdueFeeTransferredOut, "107"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.OverdueInterestTransferredOut, "108"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.OverdueInterestTransferredIn, "109"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.CollateralForClosedPositionTransferredIn, "110"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.CollateralForClosedPositionTransferredOut, "111"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.CollateralForLiquidationTransferredIn, "112"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.CollateralForLiquidationTransferredOut, "113"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.InsuranceFundTransferredIn, "114"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.InsuranceFundTransferredOut, "115"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.PlaceAnOrder, "116"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.FulfillAnOrder, "117"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.CancelAnOrder, "118"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.MerchantsUnlockDeposit, "119"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.MerchantsAddDeposit, "120"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.FiatgatewayPlaceAnOrder, "121"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.FiatgatewayCancelAnOrder, "122"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.FiatgatewayFulfillAnOrder, "123"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.JumpstartUnlocking, "124"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.ManualDeposit, "125"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.InterestDeposit, "126"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.InvestmentFeeTransferredIn, "127"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.InvestmentFeeTransferredOut, "128"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.RewardsTransferredIn, "129"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferredFromUnifiedAccount, "130"),
         new KeyValuePair<OKXFundingBillType, string>(OKXFundingBillType.TransferredToUnifiedAccount, "131"),
    };
}