using System.Text.Json.Serialization;
using CryptoExchange.Net.Converters.SystemTextJson;
using CryptoExchange.Net.Attributes;

namespace OKX.Net.Enums;
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

[JsonConverter(typeof(EnumConverter<AccountBillSubType>))]
public enum AccountBillSubType
{
    [Map("1")]
    Buy,
    [Map("2")]
    Sell,
    [Map("3")]
    OpenLong,
    [Map("4")]
    OpenShort,
    [Map("5")]
    CloseLong,
    [Map("6")]
    CloseShort,
    [Map("9")]
    InterestDeduction,
    [Map("11")]
    TransferIn,
    [Map("12")]
    TransferOut,
    [Map("14")]
    InterestDeductionMarketLoan,
    [Map("160")]
    ManualMarginIncrease,
    [Map("161")]
    ManualMarginDecrease,
    [Map("162")]
    AutoMarginIncrease,
    [Map("114")]
    AutoBuy,
    [Map("115")]
    AutoSell,
    [Map("118")]
    SystemTokenConversionTransferIn,
    [Map("119")]
    SystemTokenConversionTransferOut,
    [Map("100")]
    PartialLiquidationCloseLong,
    [Map("101")]
    PartialLiquidationCloseShort,
    [Map("102")]
    PartialLiquidationBuy,
    [Map("103")]
    PartialLiquidationSell,
    [Map("104")]
    LiquidationLong,
    [Map("105")]
    LiquidationShort,
    [Map("106")]
    LiquidationBuy,
    [Map("107")]
    LiquidationSell,
    [Map("108")]
    Clawback,
    [Map("110")]
    LiquidationTransferIn,
    [Map("111")]
    LiquidationTransferOut,
    [Map("125")]
    ADLCloseLong,
    [Map("126")]
    ADLCloseShort,
    [Map("127")]
    ADLBuy,
    [Map("128")]
    ADLSell,
    [Map("131")]
    DdhBuy,
    [Map("132")]
    DdhSell,
    [Map("170")]
    Exercised,
    [Map("171")]
    CounterpartyExercised,
    [Map("172")]
    ExpiredOTM,
    [Map("112")]
    DeliveryLong,
    [Map("113")]
    DeliveryShort,
    [Map("117")]
    DeliveryExerciseClawback,
    [Map("173")]
    FundingFeeExpense,
    [Map("174")]
    FundingFeeIncome,
    [Map("200")]
    SystemTransferIn,
    [Map("201")]
    ManuallyTransferIn,
    [Map("202")]
    SystemTransferOut,
    [Map("203")]
    ManuallyTransferOut,
    [Map("204")]
    BlockTradeBuy,
    [Map("205")]
    BlockTradeSell,
    [Map("206")]
    BlockTradeOpenLong,
    [Map("207")]
    BlockTradeOpenShort,
    [Map("208")]
    BlockTradeCloseLong,
    [Map("209")]
    BlockTradeCloseShort,
    [Map("210")]
    ManualBorrowQuickMargin,
    [Map("211")]
    ManualRepayQuickMargin,
    [Map("212")]
    AutoBorrowQuickMargin,
    [Map("213")]
    AutoRepayQuickMargin,
    [Map("16")]
    ForceRepay,
    [Map("17")]
    ForceRepayBorrowing,
    [Map("224")]
    RepayTransferIn,
    [Map("225")]
    RepayTransferOut,
    [Map("236")]
    EasyConvertIn,
    [Map("237")]
    EasyConvertOut,
    [Map("250")]
    ProfitShareExpense,
    [Map("251")]
    ProfitShareRefund,
    [Map("280")]
    SpotProfitShareExpense,
    [Map("281")]
    SpotProfitShareRefund,
    [Map("270")]
    SpreadTradingBuy,
    [Map("271")]
    SpreadTradingSell,
    [Map("272")]
    SpreadTradingOpenLong,
    [Map("273")]
    SpreadTradingOpenShort,
    [Map("274")]
    SpreadTradinCloseLong,
    [Map("275")]
    SpreadTradingCloseShort,
    [Map("290")]
    DustTransferOut,
    [Map("293")]
    FixedLoanInterestDeduction,
    [Map("294")]
    FixedLoanInterestRefund,
    [Map("295")]
    FixedLoanOverduePenalty,
    [Map("296")]
    FromStructuredOrderPlacement,
    [Map("297")]
    ToStructuredOrderPlacement,
    [Map("298")]
    FromStructuredSettlements,
    [Map("299")]
    ToStructuredSettlements,
    [Map("306")]
    ManualBorrow,
    [Map("307")]
    AutoBorrow,
    [Map("308")]
    ManualRepay,
    [Map("309")]
    AutoRepay,
    [Map("312")]
    AutoOffset,
    [Map("318")]
    ConvertIn,
    [Map("319")]
    ConvertOut,
    [Map("320")]
    SimpleBuy,
    [Map("320")]
    SimpleSell,
    [Map("355")]
    SettlementPnl,
    [Map("376")]
    CollateralBorrowAutoConversionBuy,
    [Map("377")]
    CollateralBorrowAutoConversionSell
}
